language: c
arch: amd64
dist: focal
matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      osx_image: xcode12.2
      compiler: gcc
    - os: osx
      osx_image: xcode12.2
      compiler: clang
    - os: freebsd
      compiler: clang

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make