language: c
addons:
  coverity_scan:
    project:
      name: beliefsky/sly
      version: 1.0
      description: sky
    notification_email: ibeliefsky@gmail.com
    build_command_prepend: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    build_command: make
    branch_pattern: master
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - make
    - os: osx
      osx_image: xcode12.2
      compiler: gcc
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - make
