name: freebsd
on: [ push ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: public
          retention-days: 30
      - uses: actions/checkout@v4
      - name: build in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          release: 13.2
          usesh: true
          sync: rsync
          copyback: false
          prepare: pkg install -y cmake
          run: |
            dmesg | grep -i cpu
            cd $GITHUB_WORKSPACE
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
            make
